exports.seed = async (knex) => {
      await knex('requisition_items').del();
        await knex('approvals').del();
          await knex('requisitions').del();

            const users   = await knex('users').select('id', 'role', 'email');
              const depts   = await knex('departments').select('id', 'code');
                const vendors = await knex('vendors').select('id', 'name');

                  const user   = (email) => users.find((u) => u.email === email)?.id;
                    const dept   = (code)  => depts.find((d) => d.code  === code)?.id;
                      const vendor = (name)  => vendors.find((v) => v.name === name)?.id;

                        const reqs = await knex('requisitions').insert([
                            {
                                  req_number:   'REQ-2024-1001',
                                        title:        'Laptop Computers for ICT Lab',
                                              justification:'Required for student practical sessions in the new semester',
                                                    requester_id: user('requester@ksu.edu.ng'),
                                                          dept_id:      dept('ICT'),
                                                                category:     'IT Equipment',
                                                                      priority:     'high',
                                                                            status:       'approved',
                                                                                  total_amount: 4500000,
                                                                                        vendor_id:    vendor('TechBridge Nigeria Ltd'),
                                                                                              lpo_generated:true,
                                                                                                  },
                                                                                                      {
                                                                                                            req_number:   'REQ-2024-1002',
                                                                                                                  title:        'Office Furniture for Registry',
                                                                                                                        justification:'Existing furniture is worn out and needs replacement',
                                                                                                                              requester_id: user('requester@ksu.edu.ng'),
                                                                                                                                    dept_id:      dept('REG'),
                                                                                                                                          category:     'Furniture',
                                                                                                                                                priority:     'medium',
                                                                                                                                                      status:       'pending_finance',
                                                                                                                                                            total_amount: 850000,
                                                                                                                                                                  vendor_id:    null,
                                                                                                                                                                        lpo_generated:false,
                                                                                                                                                                            },
                                                                                                                                                                                {
                                                                                                                                                                                      req_number:   'REQ-2024-1003',
                                                                                                                                                                                            title:        'Laboratory Chemicals and Reagents',
                                                                                                                                                                                                  justification:'Needed for first semester practical examinations',
                                                                                                                                                                                                        requester_id: user('requester@ksu.edu.ng'),
                                                                                                                                                                                                              dept_id:      dept('SCI'),
                                                                                                                                                                                                                    category:     'Laboratory Materials',
                                                                                                                                                                                                                          priority:     'high',
                                                                                                                                                                                                                                status:       'pending_hod',
                                                                                                                                                                                                                                      total_amount: 1200000,
                                                                                                                                                                                                                                            vendor_id:    null,
                                                                                                                                                                                                                                                  lpo_generated:false,
                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                req_number:   'REQ-2024-1004',
                                                                                                                                                                                                                                                                      title:        'Generator Diesel Supply',
                                                                                                                                                                                                                                                                            justification:'Monthly diesel supply for campus generators',
                                                                                                                                                                                                                                                                                  requester_id: user('requester@ksu.edu.ng'),
                                                                                                                                                                                                                                                                                        dept_id:      dept('WRK'),
                                                                                                                                                                                                                                                                                              category:     'Electrical Items',
                                                                                                                                                                                                                                                                                                    priority:     'urgent',
                                                                                                                                                                                                                                                                                                          status:       'rejected',
                                                                                                                                                                                                                                                                                                                total_amount: 750000,
                                                                                                                                                                                                                                                                                                                      vendor_id:    null,
                                                                                                                                                                                                                                                                                                                            lpo_generated:false,
                                                                                                                                                                                                                                                                                                                                  rejection_reason: 'Insufficient specification — please resubmit with proper documentation',
                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                        ]).returning('id');

                                                                                                                                                                                                                                                                                                                                          // Insert items for first requisition
                                                                                                                                                                                                                                                                                                                                            await knex('requisition_items').insert([
                                                                                                                                                                                                                                                                                                                                                { req_id: reqs[0].id, description: 'Dell Laptop 16GB RAM',  quantity: 10, unit: 'units', unit_price: 350000, total_price: 3500000 },
                                                                                                                                                                                                                                                                                                                                                    { req_id: reqs[0].id, description: 'HP LaserJet Printer',   quantity: 2,  unit: 'units', unit_price: 175000, total_price: 350000  },
                                                                                                                                                                                                                                                                                                                                                        { req_id: reqs[0].id, description: 'UPS 2KVA',              quantity: 5,  unit: 'units', unit_price: 80000,  total_price: 400000  },
                                                                                                                                                                                                                                                                                                                                                            { req_id: reqs[1].id, description: 'Executive Chair',        quantity: 5,  unit: 'units', unit_price: 45000,  total_price: 225000  },
                                                                                                                                                                                                                                                                                                                                                                { req_id: reqs[1].id, description: 'Office Table 1.8m',      quantity: 5,  unit: 'units', unit_price: 70000,  total_price: 350000  },
                                                                                                                                                                                                                                                                                                                                                                    { req_id: reqs[1].id, description: 'Filing Cabinet',         quantity: 5,  unit: 'units', unit_price: 55000,  total_price: 275000  },
                                                                                                                                                                                                                                                                                                                                                                        { req_id: reqs[2].id, description: 'Sodium Chloride 25kg',   quantity: 10, unit: 'bags',  unit_price: 8500,   total_price: 85000   },
                                                                                                                                                                                                                                                                                                                                                                            { req_id: reqs[2].id, description: 'Hydrochloric Acid 5L',   quantity: 20, unit: 'btls',  unit_price: 12000,  total_price: 240000  },
                                                                                                                                                                                                                                                                                                                                                                                { req_id: reqs[3].id, description: 'AGO Diesel 33,000L',     quantity: 1,  unit: 'lot',   unit_price: 750000, total_price: 750000  },
                                                                                                                                                                                                                                                                                                                                                                                  ]);
                                                                                                                                                                                                                                                                                                                                                                                  };
}