import styles from './ApprovalTimeline.module.css';
import { formatDate } from '@/utils/formatDate';

export default function ApprovalTimeline({ approvals = [] }) {
  const color = (s) =>
      s === 'approved' ? 'var(--accent)' :
          s === 'rejected' ? 'var(--red)'    : 'var(--border)';

            const icon = (s) =>
                s === 'approved' ? 'bi-check-lg'  :
                    s === 'rejected' ? 'bi-x-lg'      : 'bi-circle';

                      return (
                          <div className={styles.timeline}>
                                {approvals.map((ap, i) => {
                                        const isActive =
                                                  ap.status === 'pending' &&
                                                            (i === 0 || approvals[i - 1]?.status === 'approved');

                                                                    return (
                                                                              <div key={i} className={styles.item}>
                                                                                          {/* Line + dot */}
                                                                                                      <div className={styles.track}>
                                                                                                                    <div
                                                                                                                                    className={styles.dot}
                                                                                                                                                    style={{ borderColor: color(ap.status), background: ap.status !== 'pending' ? color(ap.status) + '22' : 'var(--panel)' }}
                                                                                                                                                                  >
                                                                                                                                                                                  <i
                                                                                                                                                                                                    className={`bi ${icon(ap.status)}`}
                                                                                                                                                                                                                      style={{ fontSize: 12, color: color(ap.status) }}
                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                  {i < approvals.length - 1 && (
                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                    className={styles.line}
                                                                                                                                                                                                                                                                                                                      style={{ background: ap.status === 'approved' ? 'var(--accent)' : 'var(--border)' }}
                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                            {/* Content */}
                                                                                                                                                                                                                                                                                                                                                                                        <div className={styles.content}>
                                                                                                                                                                                                                                                                                                                                                                                                      <div className={styles.role}>
                                                                                                                                                                                                                                                                                                                                                                                                                      {ap.role?.toUpperCase()}
                                                                                                                                                                                                                                                                                                                                                                                                                                      {isActive && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className={styles.awaitingBadge}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ● Awaiting Action
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={styles.approver}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {ap.approver?.name || 'Not assigned'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {ap.decidedAt && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className={styles.date}>{formatDate(ap.decidedAt)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {ap.comment && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={styles.comment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ color: ap.status === 'rejected' ? 'var(--red)' : 'var(--muted)' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "{ap.comment}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }