'use client';
import { useEffect, useState } from 'react';
import { useRouter }           from 'next/navigation';
import axios                   from 'axios';
import styles                  from './dashboard.module.css';
import Card                    from '@/components/ui/Card/Card';
import StatCard                from '@/components/ui/StatCard/StatCard';
import Badge                   from '@/components/ui/Badge/Badge';
import BudgetBar               from '@/components/shared/BudgetBar/BudgetBar';
import Spinner                 from '@/components/ui/Spinner/Spinner';
import { useAuthStore }        from '@/store/authStore';
import { formatNaira }         from '@/utils/formatCurrency';
import { formatDate }          from '@/utils/formatDate';

export default function AdminDashboard() {
  const { token }             = useAuthStore();
    const router                = useRouter();
      const [summary, setSummary] = useState(null);
        const [reqs,    setReqs]    = useState([]);
          const [budget,  setBudget]  = useState(null);
            const [loading, setLoading] = useState(true);

              useEffect(() => {
                  const h = { Authorization: `Bearer ${token}` };
                      Promise.all([
                            axios.get('/api/reports/summary',     { headers: h }),
                                  axios.get('/api/requisitions',        { headers: h }),
                                        axios.get('/api/budget?summary=true', { headers: h }),
                                            ]).then(([r1, r2, r3]) => {
                                                  setSummary(r1.data.data || null);
                                                        setReqs(r2.data.data    || []);
                                                              setBudget(r3.data.data  || null);
                                                                  }).finally(() => setLoading(false));
                                                                    }, [token]);

                                                                      if (loading) return (
                                                                          <div style={{ display: 'flex', justifyContent: 'center', padding: 60 }}>
                                                                                <Spinner />
                                                                                    </div>
                                                                                      );

                                                                                        const recent = reqs.slice(0, 5);

                                                                                          return (
                                                                                              <div className={styles.page}>
                                                                                                    <div className={styles.welcome}>
                                                                                                            <div className={styles.welcomeText}>
                                                                                                                      <h2>Admin Dashboard ⚙️</h2>
                                                                                                                                <p>Full system overview — KSU Procurement FY {summary?.fiscalYear}.</p>
                                                                                                                                        </div>
                                                                                                                                              </div>

                                                                                                                                                    <div className={styles.statsGrid}>
                                                                                                                                                            <StatCard label="Total Requisitions" value={summary?.total    || 0}                    icon="bi-clipboard-text"  />
                                                                                                                                                                    <StatCard label="Approved"           value={summary?.approved || 0} accent="var(--accent)" icon="bi-check-circle" />
                                                                                                                                                                            <StatCard label="Pending"            value={summary?.pending  || 0} accent="var(--gold)"   icon="bi-hourglass"    />
                                                                                                                                                                                    <StatCard label="Total Value"        value={formatNaira(summary?.totalValue || 0)} accent="var(--blue)" icon="bi-cash-stack" />
                                                                                                                                                                                          </div>

                                                                                                                                                                                                <div className={styles.grid2}>
                                                                                                                                                                                                        {/* Recent activity */}
                                                                                                                                                                                                                <Card>
                                                                                                                                                                                                                          <div className={styles.sectionHeader}>
                                                                                                                                                                                                                                      <div className={styles.sectionTitle}>Recent Requisitions</div>
                                                                                                                                                                                                                                                  <button className={styles.viewAll} onClick={() => router.push('/requisitions')}>
                                                                                                                                                                                                                                                                View all →
                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                {recent.map((r) => (
                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                          key={r._id}
                                                                                                                                                                                                                                                                                                                                        className={styles.reqItem}
                                                                                                                                                                                                                                                                                                                                                      onClick={() => router.push(`/requisitions/${r._id}`)}
                                                                                                                                                                                                                                                                                                                                                                    style={{ cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                              <div className={styles.reqInfo}>
                                                                                                                                                                                                                                                                                                                                                                                                              <div className={styles.reqTitle}>{r.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div className={styles.reqMeta}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                {r.department?.name} • {r.requester?.name} • {formatDate(r.createdAt)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className={styles.reqRight}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className={styles.reqAmount}>{formatNaira(r.totalAmount)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: 4 }}><Badge status={r.status} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Budget */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className={styles.sectionHeader}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className={styles.sectionTitle}>Institution Budget</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className={styles.viewAll} onClick={() => router.push('/budget')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Full view →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {(budget?.departments || []).slice(0, 6).map((b) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <BudgetBar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={b.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label={b.department?.name || '—'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              allocated={b.allocated}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            spent={b.spent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          committed={b.committed}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Quick actions */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={styles.grid4}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { label: 'Requisitions', icon: 'bi-clipboard-text',   href: '/requisitions', color: 'var(--accent)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { label: 'Approvals',    icon: 'bi-check-circle',     href: '/approvals',    color: 'var(--gold)'   },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { label: 'Vendors',      icon: 'bi-building',         href: '/vendors',      color: 'var(--blue)'   },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { label: 'LPO / Orders', icon: 'bi-file-earmark-text',href: '/lpo',          color: 'var(--purple)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { label: 'Budget',       icon: 'bi-cash-stack',       href: '/budget',       color: 'var(--accent)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { label: 'Reports',      icon: 'bi-bar-chart-line',   href: '/reports',      color: 'var(--gold)'   },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { label: 'Audit Trail',  icon: 'bi-search',           href: '/audit',        color: 'var(--blue)'   },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { label: 'Settings',     icon: 'bi-gear',             href: '/settings',     color: 'var(--muted)'  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ].map((a) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={a.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={styles.quickAction}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => router.push(a.href)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <i className={`bi ${a.icon}`} style={{ fontSize: 20, color: a.color, display: 'block', marginBottom: 8 }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={styles.qaLabel}>{a.label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
