'use client';
import { useEffect, useState } from 'react';
import { useRouter }           from 'next/navigation';
import axios                   from 'axios';
import styles                  from '@/app/(dashboard)/dashboard.module.css';
import Card                    from '@/components/ui/Card/Card';
import StatCard                from '@/components/ui/StatCard/StatCard';
import BudgetBar               from '@/components/shared/BudgetBar/BudgetBar';
import Button                  from '@/components/ui/Button/Button';
import Spinner                 from '@/components/ui/Spinner/Spinner';
import { useAuthStore }        from '@/store/authStore';
import { formatNaira }         from '@/utils/formatCurrency';

export default function FinanceDashboard() {
  const { token }             = useAuthStore();
    const router                = useRouter();
      const [queue,   setQueue]   = useState([]);
        const [budget,  setBudget]  = useState(null);
          const [loading, setLoading] = useState(true);

            useEffect(() => {
                const h = { Authorization: `Bearer ${token}` };
                    Promise.all([
                          axios.get('/api/approvals',         { headers: h }),
                                axios.get('/api/budget?summary=true', { headers: h }),
                                    ]).then(([r1, r2]) => {
                                          setQueue(r1.data.data  || []);
                                                setBudget(r2.data.data || null);
                                                    }).finally(() => setLoading(false));
                                                      }, [token]);

                                                        if (loading) return (
                                                            <div style={{ display: 'flex', justifyContent: 'center', padding: 60 }}>
                                                                  <Spinner />
                                                                      </div>
                                                                        );

                                                                          return (
                                                                              <div className={styles.page}>
                                                                                    <div className={styles.welcome}>
                                                                                            <div className={styles.welcomeText}>
                                                                                                      <h2>Finance Dashboard 💰</h2>
                                                                                                                <p>Monitor budget utilization and approve financial commitments.</p>
                                                                                                                        </div>
                                                                                                                                {queue.length > 0 && (
                                                                                                                                          <Button onClick={() => router.push('/approvals')} variant="gold" icon="bi-bell">
                                                                                                                                                      {queue.length} Pending Finance Approval
                                                                                                                                                                </Button>
                                                                                                                                                                        )}
                                                                                                                                                                              </div>

                                                                                                                                                                                    <div className={styles.statsGrid}>
                                                                                                                                                                                            <StatCard
                                                                                                                                                                                                      label="Total Budget"
                                                                                                                                                                                                                value={formatNaira(budget?.totalAllocated || 0)}
                                                                                                                                                                                                                          icon="bi-bank"
                                                                                                                                                                                                                                    accent="var(--text)"
                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                    <StatCard
                                                                                                                                                                                                                                                              label="Total Spent"
                                                                                                                                                                                                                                                                        value={formatNaira(budget?.totalSpent || 0)}
                                                                                                                                                                                                                                                                                  icon="bi-arrow-up-circle"
                                                                                                                                                                                                                                                                                            accent="var(--red)"
                                                                                                                                                                                                                                                                                                      sub={`${budget?.totalAllocated ? Math.round((budget.totalSpent / budget.totalAllocated) * 100) : 0}% of budget`}
                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                      <StatCard
                                                                                                                                                                                                                                                                                                                                label="Committed"
                                                                                                                                                                                                                                                                                                                                          value={formatNaira(budget?.totalCommitted || 0)}
                                                                                                                                                                                                                                                                                                                                                    icon="bi-hourglass-split"
                                                                                                                                                                                                                                                                                                                                                              accent="var(--gold)"
                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                              <StatCard
                                                                                                                                                                                                                                                                                                                                                                                        label="Available"
                                                                                                                                                                                                                                                                                                                                                                                                  value={formatNaira(budget?.totalAvailable || 0)}
                                                                                                                                                                                                                                                                                                                                                                                                            icon="bi-wallet2"
                                                                                                                                                                                                                                                                                                                                                                                                                      accent="var(--accent)"
                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={styles.grid2}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Budget by dept */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.sectionHeader}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={styles.sectionTitle}>Budget Utilization by Department</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className={styles.viewAll} onClick={() => router.push('/budget')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Full view →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {(budget?.departments || []).slice(0, 6).map((b) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <BudgetBar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={b.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  label={b.department?.name || '—'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                allocated={b.allocated}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              spent={b.spent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            committed={b.committed}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Approval queue */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.sectionHeader}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={styles.sectionTitle}>Pending Finance Approval</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className={styles.viewAll} onClick={() => router.push('/approvals')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          View all →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {queue.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ textAlign: 'center', padding: '32px 0', color: 'var(--muted)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i className="bi bi-check-all" style={{ fontSize: 36, color: 'var(--accent)' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ marginTop: 8 }}>No pending approvals</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    queue.slice(0, 4).map((r) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={r._id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={styles.approvalCard}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => router.push(`/requisitions/${r._id}`)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={styles.approvalId}>{r.reqNumber}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={styles.approvalTitle}>{r.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={styles.approvalMeta}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {r.department?.name} •
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <strong style={{ color: 'var(--accent)', marginLeft: 4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {formatNaira(r.totalAmount)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
