'use client';
import { useEffect, useState } from 'react';
import { useRouter }           from 'next/navigation';
import axios                   from 'axios';
import styles                  from '@/app/(dashboard)/dashboard.module.css';
import Card                    from '@/components/ui/Card/Card';
import StatCard                from '@/components/ui/StatCard/StatCard';
import Badge                   from '@/components/ui/Badge/Badge';
import Button                  from '@/components/ui/Button/Button';
import Spinner                 from '@/components/ui/Spinner/Spinner';
import { useAuthStore }        from '@/store/authStore';
import { formatNaira }         from '@/utils/formatCurrency';
import { formatDate }          from '@/utils/formatDate';

export default function HODDashboard() {
  const { user, token }     = useAuthStore();
    const router              = useRouter();
      const [reqs,    setReqs]  = useState([]);
        const [queue,   setQueue] = useState([]);
          const [loading, setLoading] = useState(true);

            useEffect(() => {
                const headers = { Authorization: `Bearer ${token}` };
                    Promise.all([
                          axios.get('/api/requisitions',     { headers }),
                                axios.get('/api/approvals',        { headers }),
                                    ]).then(([r1, r2]) => {
                                          setReqs(r1.data.data  || []);
                                                setQueue(r2.data.data || []);
                                                    }).finally(() => setLoading(false));
                                                      }, [token]);

                                                        const total    = reqs.length;
                                                          const pending  = reqs.filter((r) => r.status === 'pending_hod').length;
                                                            const approved = reqs.filter((r) => r.status !== 'draft' && r.status !== 'pending_hod').length;
                                                              const totalVal = reqs.reduce((s, r) => s + (r.totalAmount || 0), 0);

                                                                if (loading) return (
                                                                    <div style={{ display: 'flex', justifyContent: 'center', padding: 60 }}>
                                                                          <Spinner />
                                                                              </div>
                                                                                );

                                                                                  return (
                                                                                      <div className={styles.page}>
                                                                                            <div className={styles.welcome}>
                                                                                                    <div className={styles.welcomeText}>
                                                                                                              <h2>HOD Dashboard 📋</h2>
                                                                                                                        <p>Review and approve requisitions from your department.</p>
                                                                                                                                </div>
                                                                                                                                        {queue.length > 0 && (
                                                                                                                                                  <Button onClick={() => router.push('/approvals')} variant="gold" icon="bi-bell">
                                                                                                                                                              {queue.length} Pending Approval{queue.length > 1 ? 's' : ''}
                                                                                                                                                                        </Button>
                                                                                                                                                                                )}
                                                                                                                                                                                      </div>

                                                                                                                                                                                            <div className={styles.statsGrid}>
                                                                                                                                                                                                    <StatCard label="Dept Requisitions" value={total}            icon="bi-clipboard-text" />
                                                                                                                                                                                                            <StatCard label="Awaiting My Action" value={queue.length}    icon="bi-hourglass"      accent="var(--gold)"   />
                                                                                                                                                                                                                    <StatCard label="Passed HOD Review"  value={approved}        icon="bi-check2-circle"  accent="var(--accent)" />
                                                                                                                                                                                                                            <StatCard label="Dept Total Value"   value={formatNaira(totalVal)} icon="bi-cash"     accent="var(--blue)"   />
                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                        <div className={styles.grid2}>
                                                                                                                                                                                                                                                {/* Pending approval queue */}
                                                                                                                                                                                                                                                        <Card>
                                                                                                                                                                                                                                                                  <div className={styles.sectionHeader}>
                                                                                                                                                                                                                                                                              <div className={styles.sectionTitle}>
                                                                                                                                                                                                                                                                                            Pending My Approval
                                                                                                                                                                                                                                                                                                          {queue.length > 0 && (
                                                                                                                                                                                                                                                                                                                          <span style={{
                                                                                                                                                                                                                                                                                                                                            marginLeft:    8,
                                                                                                                                                                                                                                                                                                                                                              background:    'var(--gold)',
                                                                                                                                                                                                                                                                                                                                                                                color:         '#000',
                                                                                                                                                                                                                                                                                                                                                                                                  fontSize:      11,
                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight:    700,
                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius:  10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding:       '2px 8px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {queue.length}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className={styles.viewAll} onClick={() => router.push('/approvals')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              View queue →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {queue.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ textAlign: 'center', padding: '32px 0', color: 'var(--muted)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i className="bi bi-check-all" style={{ fontSize: 36, color: 'var(--accent)' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginTop: 8 }}>All clear! No pending approvals.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        queue.slice(0, 4).map((r) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={r._id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={styles.approvalCard}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => router.push(`/requisitions/${r._id}`)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.approvalId}>{r.reqNumber}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.approvalTitle}>{r.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.approvalMeta}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {r.requester?.name} •
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong style={{ color: 'var(--accent)', marginLeft: 4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {formatNaira(r.totalAmount)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style={{ marginLeft: 6 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Badge status={r.status} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Department requisitions */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className={styles.sectionTitle}>Department Requisitions</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {reqs.slice(0, 5).map((r) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={r._id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={styles.reqItem}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => router.push(`/requisitions/${r._id}`)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.reqInfo}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.reqTitle}>{r.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.reqMeta}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {r.requester?.name} • {formatDate(r.createdAt)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className={styles.reqRight}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className={styles.reqAmount}>{formatNaira(r.totalAmount)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ marginTop: 4 }}><Badge status={r.status} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
